theme: midnight
title: Welcome to Zak's homepage
description: Hosting coursework

# Zachary Domingo
Welcome to my site
- Coursework
- [Forecasting Crime Patterns in Bellingham, WA](https://cedar.wwu.edu/cgi/viewcontent.cgi?article=1447&context=scholwk)

